pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

trigger:
  - developer

stages:
  - stage: 'buildnpush'
    displayName: 'Build docker image and push'
    jobs:
      - job: 'buildnpush'
        displayName: 'Build docker image and push to registry'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker'
              repository: 'shivakrishna99/azdevopsstudentsregister'
              command: 'buildAndPush'
              tags: "latest"
          - script: 'kubectl apply -f kubernetes/mysql-deploy.yaml'
