---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
patchesStrategicMerge
  - patch.yaml  # Include any patches specific to dev environment
